### ISSUE TITLE
Latest version does not wait for downloads

### ISSUE THREAD

**Issue by weggis** [LogicInteractive/KontentumClient#10]
Latest version seems to launch application before downloads are complete. This affects AIR application which then also starts to download missing files.. Last observed on build version 2021-06-23 18:01:52 (KOKO/inspiria)

**Comment by datee** [comment]
Fixed in : https://github.com/LogicInteractive/KontentumClient/commit/f14970558101b7e38d46bc301aa3a0df7f2d0b32
